name: "Publish Docs :: Core"

on: workflow_dispatch

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    outputs:
      pypz-version: ${{ steps.version.outputs.value }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install
      run: |
        python -m pip install --upgrade pip
        python -m pip install pyyaml
        python -m pip install -e ./core/.[docs]
    - name: Build
      run: |
        sphinx-build ./core/docs ./core/docs/_build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./core/docs/_build
