name: "Publish :: Docs"

on: workflow_dispatch

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install
      run: |
        sudo apt install graphviz
        python -m pip install --upgrade pip
        python -m pip install pyyaml
        python -m pip install -r requirements.txt
        python -m pip install -r ./docs/requirements.txt
    - name: Build
      run: |
        sphinx-build ./docs ./docs/_build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build
